function init(self)
    msg.post(".", "acquire_input_focus")
  
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

function on_message(self, message_id, message, sender)
    if message_id == hash("флоппа_у_відрі") then
        msg.post("#left_door", "play_animation", {id = hash("флоппа_у_відрі")})
    end    
end

function on_input(self, action_id, action)
end

function on_reload(self)
end



