function init(self)
	msg.post(".", "acquire_input_focus")
	
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		left_button = gui.get_node("left_button")
		right_button = gui.get_node("right_button")
		if gui.pick_node(left_button, action.x, action.y) then
			print("Left button")
		elseif gui.pick_node(right_button, action.x, action.y) then
			print("Right button")
		end
	end
end
